openapi: 3.0.0
info:
  title: KitSoft Test API
  description: REST API for KitSoft Test Project
  termsOfService: ''
  contact:
    email: vlad.betcun@gmail.com
  version: v1.0
servers:
  - url: http://localhost:8080/api
    description: Test server
paths:
  /test/ping:
    get:
      tags:
        - System
      summary: Checks server availability
      description: Get information of server availability and request duration
      responses:
        200:
          description: Successful fetching data
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: string
                    example: pong
                  meta:
                    type: object
                    properties:
                      handlingTime:
                        type: number
                        format: float
                        example: 123.456
        404:
          $ref: '#components/responses/404'
        405:
          $ref: '#components/responses/405'
components:
  schemas:
    Error:
      properties:
        message:
          type: string
  responses:
    404:
      description: 'Requested Resource not found'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: 'Not Found'
    405:
      description: 'Method Not Allowed'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: 'Method Not Allowed'
    409:
      description: 'Conflict'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: 'Conflict'
    422:
      description: 'Unprocessable Entity'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: 'Unprocessable Entity'
tags:
  - name: System
    description: System Endpoints
